### ISSUE TITLE
`netperf -1` panics

### ISSUE THREAD

**Issue by howardjohn** [AhmedSoliman/netperf#4]
```
$ RUST_BACKTRACE=1 netperf -1
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /usr/local/google/home/howardjohn/.cargo/registry/src/github.com-1ecc6299db9ec823/netperf-0.2.3/src/client.rs:15:56
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
   3: netperf::main::{{closure}}
   4: std::thread::local::LocalKey<T>::with
   5: tokio::park::thread::CachedParkThread::block_on
   6: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
   7: tokio::runtime::Runtime::block_on
   8: netperf::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

A cursory look seems to suggest that `one_off` is just a flag but not implemented, so it ends up hitting the wrong code path

**Comment by AhmedSoliman** [comment]
Thanks for reporting this. I've just pushed `0.2.4` which removes this flag until it gets implemented.
